openapi: 3.0.3
info:
  title: Mixologist
  version: 1.0.0
paths:
  /ingredients:
    get:
      operationId: getIngredients
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientsResponse'
  /potential-cocktails:
    post:
      operationId: postPotential-cocktails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PotentialCocktailsJsonPayload'
        required: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PotentialCocktailsResponse'
        '400':
          description: 'Invalid value for: body'
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    Amount:
      oneOf:
      - $ref: '#/components/schemas/Centiliter'
      - $ref: '#/components/schemas/Dash'
      - $ref: '#/components/schemas/Drop'
      - $ref: '#/components/schemas/Pinch'
      - $ref: '#/components/schemas/Relative'
      - $ref: '#/components/schemas/Slice'
      - $ref: '#/components/schemas/Splash'
      - $ref: '#/components/schemas/Sprig'
      - $ref: '#/components/schemas/Teaspoon'
      - $ref: '#/components/schemas/ToTaste'
      - $ref: '#/components/schemas/TopOff'
      discriminator:
        propertyName: discriminator
        mapping:
          Centiliter: '#/components/schemas/Centiliter'
          Dash: '#/components/schemas/Dash'
          Drop: '#/components/schemas/Drop'
          Pinch: '#/components/schemas/Pinch'
          Relative: '#/components/schemas/Relative'
          Slice: '#/components/schemas/Slice'
          Splash: '#/components/schemas/Splash'
          Sprig: '#/components/schemas/Sprig'
          Teaspoon: '#/components/schemas/Teaspoon'
          ToTaste: '#/components/schemas/ToTaste'
          TopOff: '#/components/schemas/TopOff'
    Centiliter:
      required:
      - quantity
      - discriminator
      type: object
      properties:
        quantity:
          type: number
          format: double
        discriminator:
          type: string
    ChampagneFlute:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    ChampagneTulip:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    Cocktail:
      required:
      - name
      - glass
      type: object
      properties:
        name:
          type: string
        glass:
          $ref: '#/components/schemas/Glass'
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/CocktailIngredient'
    CocktailIngredient:
      required:
      - ingredient
      - amount
      type: object
      properties:
        ingredient:
          $ref: '#/components/schemas/Ingredient'
        amount:
          $ref: '#/components/schemas/Amount'
    Collins:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    Dash:
      required:
      - quantity
      - discriminator
      type: object
      properties:
        quantity:
          type: integer
          format: int32
        discriminator:
          type: string
    Drop:
      required:
      - quantity
      - discriminator
      type: object
      properties:
        quantity:
          type: integer
          format: int32
        discriminator:
          type: string
    Glass:
      oneOf:
      - $ref: '#/components/schemas/ChampagneFlute'
      - $ref: '#/components/schemas/ChampagneTulip'
      - $ref: '#/components/schemas/Collins'
      - $ref: '#/components/schemas/Highball'
      - $ref: '#/components/schemas/HotDrink'
      - $ref: '#/components/schemas/Hurricane'
      - $ref: '#/components/schemas/Margarita'
      - $ref: '#/components/schemas/Martini'
      - $ref: '#/components/schemas/OldFashioned'
      - $ref: '#/components/schemas/Shot'
      - $ref: '#/components/schemas/WhiteWine'
      discriminator:
        propertyName: discriminator
        mapping:
          ChampagneFlute: '#/components/schemas/ChampagneFlute'
          ChampagneTulip: '#/components/schemas/ChampagneTulip'
          Collins: '#/components/schemas/Collins'
          Highball: '#/components/schemas/Highball'
          HotDrink: '#/components/schemas/HotDrink'
          Hurricane: '#/components/schemas/Hurricane'
          Margarita: '#/components/schemas/Margarita'
          Martini: '#/components/schemas/Martini'
          OldFashioned: '#/components/schemas/OldFashioned'
          Shot: '#/components/schemas/Shot'
          WhiteWine: '#/components/schemas/WhiteWine'
    Highball:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    HotDrink:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    Hurricane:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    Ingredient:
      required:
      - name
      type: object
      properties:
        name:
          type: string
    IngredientsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
    Margarita:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    Martini:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    OldFashioned:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    Pinch:
      required:
      - quantity
      - discriminator
      type: object
      properties:
        quantity:
          type: integer
          format: int32
        discriminator:
          type: string
    PotentialCocktail:
      required:
      - cocktail
      type: object
      properties:
        cocktail:
          $ref: '#/components/schemas/Cocktail'
        missingIngredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
    PotentialCocktailsJsonPayload:
      type: object
      properties:
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
    PotentialCocktailsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PotentialCocktail'
    Relative:
      required:
      - quantity
      - discriminator
      type: object
      properties:
        quantity:
          type: number
          format: double
        discriminator:
          type: string
    Shot:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    Slice:
      required:
      - quantity
      - discriminator
      type: object
      properties:
        quantity:
          type: number
          format: double
        discriminator:
          type: string
    Splash:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    Sprig:
      required:
      - quantity
      - discriminator
      type: object
      properties:
        quantity:
          type: integer
          format: int32
        discriminator:
          type: string
    Teaspoon:
      required:
      - quantity
      - discriminator
      type: object
      properties:
        quantity:
          type: number
          format: double
        discriminator:
          type: string
    ToTaste:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    TopOff:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
    WhiteWine:
      required:
      - discriminator
      type: object
      properties:
        discriminator:
          type: string
