name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "sbt"
      - name: Ensure Open API Spec is Up-to-date
        working-directory: api
        run: |
          mv ../open-api-spec.yaml ../original-open-api-spec.yaml
          MIXOLOGIST_API_VERSION=$(sbt -Dsbt.supershell=false -Dsbt.log.noformat=true -error "print version") sbt "runMain mixologist.GenerateOpenApiSpec"
          diff -q ../open-api-spec.yaml ../original-open-api-spec.yaml
      - name: Run tests
        run: sbt test
        working-directory: api

  test-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.2
      - name: Install dependencies
        run: npm ci
        working-directory: web
      - run: npm run lint
        working-directory: web
      - run: npm test
        working-directory: web
